/*
My API

This is the API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package main

import (
	"encoding/json"
	"fmt"
)

// checks if the ApiGetExectableJobPost200ResponseInnerVolsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiGetExectableJobPost200ResponseInnerVolsInner{}

// ApiGetExectableJobPost200ResponseInnerVolsInner struct for ApiGetExectableJobPost200ResponseInnerVolsInner
type ApiGetExectableJobPost200ResponseInnerVolsInner struct {
	Resolved string `json:"resolved"`
	Target string `json:"target"`
	Type string `json:"type"`
	Staged bool `json:"staged"`
}

type _ApiGetExectableJobPost200ResponseInnerVolsInner ApiGetExectableJobPost200ResponseInnerVolsInner

// NewApiGetExectableJobPost200ResponseInnerVolsInner instantiates a new ApiGetExectableJobPost200ResponseInnerVolsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiGetExectableJobPost200ResponseInnerVolsInner(resolved string, target string, type_ string, staged bool) *ApiGetExectableJobPost200ResponseInnerVolsInner {
	this := ApiGetExectableJobPost200ResponseInnerVolsInner{}
	this.Resolved = resolved
	this.Target = target
	this.Type = type_
	this.Staged = staged
	return &this
}

// NewApiGetExectableJobPost200ResponseInnerVolsInnerWithDefaults instantiates a new ApiGetExectableJobPost200ResponseInnerVolsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiGetExectableJobPost200ResponseInnerVolsInnerWithDefaults() *ApiGetExectableJobPost200ResponseInnerVolsInner {
	this := ApiGetExectableJobPost200ResponseInnerVolsInner{}
	return &this
}

// GetResolved returns the Resolved field value
func (o *ApiGetExectableJobPost200ResponseInnerVolsInner) GetResolved() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Resolved
}

// GetResolvedOk returns a tuple with the Resolved field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInnerVolsInner) GetResolvedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resolved, true
}

// SetResolved sets field value
func (o *ApiGetExectableJobPost200ResponseInnerVolsInner) SetResolved(v string) {
	o.Resolved = v
}

// GetTarget returns the Target field value
func (o *ApiGetExectableJobPost200ResponseInnerVolsInner) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInnerVolsInner) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *ApiGetExectableJobPost200ResponseInnerVolsInner) SetTarget(v string) {
	o.Target = v
}

// GetType returns the Type field value
func (o *ApiGetExectableJobPost200ResponseInnerVolsInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInnerVolsInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ApiGetExectableJobPost200ResponseInnerVolsInner) SetType(v string) {
	o.Type = v
}

// GetStaged returns the Staged field value
func (o *ApiGetExectableJobPost200ResponseInnerVolsInner) GetStaged() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Staged
}

// GetStagedOk returns a tuple with the Staged field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInnerVolsInner) GetStagedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Staged, true
}

// SetStaged sets field value
func (o *ApiGetExectableJobPost200ResponseInnerVolsInner) SetStaged(v bool) {
	o.Staged = v
}

func (o ApiGetExectableJobPost200ResponseInnerVolsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiGetExectableJobPost200ResponseInnerVolsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resolved"] = o.Resolved
	toSerialize["target"] = o.Target
	toSerialize["type"] = o.Type
	toSerialize["staged"] = o.Staged
	return toSerialize, nil
}

func (o *ApiGetExectableJobPost200ResponseInnerVolsInner) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resolved",
		"target",
		"type",
		"staged",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiGetExectableJobPost200ResponseInnerVolsInner := _ApiGetExectableJobPost200ResponseInnerVolsInner{}

	err = json.Unmarshal(bytes, &varApiGetExectableJobPost200ResponseInnerVolsInner)

	if err != nil {
		return err
	}

	*o = ApiGetExectableJobPost200ResponseInnerVolsInner(varApiGetExectableJobPost200ResponseInnerVolsInner)

	return err
}

type NullableApiGetExectableJobPost200ResponseInnerVolsInner struct {
	value *ApiGetExectableJobPost200ResponseInnerVolsInner
	isSet bool
}

func (v NullableApiGetExectableJobPost200ResponseInnerVolsInner) Get() *ApiGetExectableJobPost200ResponseInnerVolsInner {
	return v.value
}

func (v *NullableApiGetExectableJobPost200ResponseInnerVolsInner) Set(val *ApiGetExectableJobPost200ResponseInnerVolsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiGetExectableJobPost200ResponseInnerVolsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiGetExectableJobPost200ResponseInnerVolsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiGetExectableJobPost200ResponseInnerVolsInner(val *ApiGetExectableJobPost200ResponseInnerVolsInner) *NullableApiGetExectableJobPost200ResponseInnerVolsInner {
	return &NullableApiGetExectableJobPost200ResponseInnerVolsInner{value: val, isSet: true}
}

func (v NullableApiGetExectableJobPost200ResponseInnerVolsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiGetExectableJobPost200ResponseInnerVolsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


