/*
My API

This is the API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package main

import (
	"encoding/json"
	"fmt"
)

// checks if the Directory type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Directory{}

// Directory struct for Directory
type Directory struct {
	Class string `json:"class"`
	Location *string `json:"location,omitempty"`
	Path *string `json:"path,omitempty"`
	Basename *string `json:"basename,omitempty"`
	Dirname *string `json:"dirname,omitempty"`
	Writable *bool `json:"writable,omitempty"`
	Listing []FileAllOfSecondaryFilesInner `json:"listing,omitempty"`
}

type _Directory Directory

// NewDirectory instantiates a new Directory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDirectory(class string) *Directory {
	this := Directory{}
	this.Class = class
	return &this
}

// NewDirectoryWithDefaults instantiates a new Directory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDirectoryWithDefaults() *Directory {
	this := Directory{}
	return &this
}

// GetClass returns the Class field value
func (o *Directory) GetClass() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Class
}

// GetClassOk returns a tuple with the Class field value
// and a boolean to check if the value has been set.
func (o *Directory) GetClassOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Class, true
}

// SetClass sets field value
func (o *Directory) SetClass(v string) {
	o.Class = v
}

// GetLocation returns the Location field value if set, zero value otherwise.
func (o *Directory) GetLocation() string {
	if o == nil || IsNil(o.Location) {
		var ret string
		return ret
	}
	return *o.Location
}

// GetLocationOk returns a tuple with the Location field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Directory) GetLocationOk() (*string, bool) {
	if o == nil || IsNil(o.Location) {
		return nil, false
	}
	return o.Location, true
}

// HasLocation returns a boolean if a field has been set.
func (o *Directory) HasLocation() bool {
	if o != nil && !IsNil(o.Location) {
		return true
	}

	return false
}

// SetLocation gets a reference to the given string and assigns it to the Location field.
func (o *Directory) SetLocation(v string) {
	o.Location = &v
}

// GetPath returns the Path field value if set, zero value otherwise.
func (o *Directory) GetPath() string {
	if o == nil || IsNil(o.Path) {
		var ret string
		return ret
	}
	return *o.Path
}

// GetPathOk returns a tuple with the Path field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Directory) GetPathOk() (*string, bool) {
	if o == nil || IsNil(o.Path) {
		return nil, false
	}
	return o.Path, true
}

// HasPath returns a boolean if a field has been set.
func (o *Directory) HasPath() bool {
	if o != nil && !IsNil(o.Path) {
		return true
	}

	return false
}

// SetPath gets a reference to the given string and assigns it to the Path field.
func (o *Directory) SetPath(v string) {
	o.Path = &v
}

// GetBasename returns the Basename field value if set, zero value otherwise.
func (o *Directory) GetBasename() string {
	if o == nil || IsNil(o.Basename) {
		var ret string
		return ret
	}
	return *o.Basename
}

// GetBasenameOk returns a tuple with the Basename field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Directory) GetBasenameOk() (*string, bool) {
	if o == nil || IsNil(o.Basename) {
		return nil, false
	}
	return o.Basename, true
}

// HasBasename returns a boolean if a field has been set.
func (o *Directory) HasBasename() bool {
	if o != nil && !IsNil(o.Basename) {
		return true
	}

	return false
}

// SetBasename gets a reference to the given string and assigns it to the Basename field.
func (o *Directory) SetBasename(v string) {
	o.Basename = &v
}

// GetDirname returns the Dirname field value if set, zero value otherwise.
func (o *Directory) GetDirname() string {
	if o == nil || IsNil(o.Dirname) {
		var ret string
		return ret
	}
	return *o.Dirname
}

// GetDirnameOk returns a tuple with the Dirname field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Directory) GetDirnameOk() (*string, bool) {
	if o == nil || IsNil(o.Dirname) {
		return nil, false
	}
	return o.Dirname, true
}

// HasDirname returns a boolean if a field has been set.
func (o *Directory) HasDirname() bool {
	if o != nil && !IsNil(o.Dirname) {
		return true
	}

	return false
}

// SetDirname gets a reference to the given string and assigns it to the Dirname field.
func (o *Directory) SetDirname(v string) {
	o.Dirname = &v
}

// GetWritable returns the Writable field value if set, zero value otherwise.
func (o *Directory) GetWritable() bool {
	if o == nil || IsNil(o.Writable) {
		var ret bool
		return ret
	}
	return *o.Writable
}

// GetWritableOk returns a tuple with the Writable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Directory) GetWritableOk() (*bool, bool) {
	if o == nil || IsNil(o.Writable) {
		return nil, false
	}
	return o.Writable, true
}

// HasWritable returns a boolean if a field has been set.
func (o *Directory) HasWritable() bool {
	if o != nil && !IsNil(o.Writable) {
		return true
	}

	return false
}

// SetWritable gets a reference to the given bool and assigns it to the Writable field.
func (o *Directory) SetWritable(v bool) {
	o.Writable = &v
}

// GetListing returns the Listing field value if set, zero value otherwise.
func (o *Directory) GetListing() []FileAllOfSecondaryFilesInner {
	if o == nil || IsNil(o.Listing) {
		var ret []FileAllOfSecondaryFilesInner
		return ret
	}
	return o.Listing
}

// GetListingOk returns a tuple with the Listing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Directory) GetListingOk() ([]FileAllOfSecondaryFilesInner, bool) {
	if o == nil || IsNil(o.Listing) {
		return nil, false
	}
	return o.Listing, true
}

// HasListing returns a boolean if a field has been set.
func (o *Directory) HasListing() bool {
	if o != nil && !IsNil(o.Listing) {
		return true
	}

	return false
}

// SetListing gets a reference to the given []FileAllOfSecondaryFilesInner and assigns it to the Listing field.
func (o *Directory) SetListing(v []FileAllOfSecondaryFilesInner) {
	o.Listing = v
}

func (o Directory) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Directory) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["class"] = o.Class
	if !IsNil(o.Location) {
		toSerialize["location"] = o.Location
	}
	if !IsNil(o.Path) {
		toSerialize["path"] = o.Path
	}
	if !IsNil(o.Basename) {
		toSerialize["basename"] = o.Basename
	}
	if !IsNil(o.Dirname) {
		toSerialize["dirname"] = o.Dirname
	}
	if !IsNil(o.Writable) {
		toSerialize["writable"] = o.Writable
	}
	if !IsNil(o.Listing) {
		toSerialize["listing"] = o.Listing
	}
	return toSerialize, nil
}

func (o *Directory) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"class",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDirectory := _Directory{}

	err = json.Unmarshal(bytes, &varDirectory)

	if err != nil {
		return err
	}

	*o = Directory(varDirectory)

	return err
}

type NullableDirectory struct {
	value *Directory
	isSet bool
}

func (v NullableDirectory) Get() *Directory {
	return v.value
}

func (v *NullableDirectory) Set(val *Directory) {
	v.value = val
	v.isSet = true
}

func (v NullableDirectory) IsSet() bool {
	return v.isSet
}

func (v *NullableDirectory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDirectory(val *Directory) *NullableDirectory {
	return &NullableDirectory{value: val, isSet: true}
}

func (v NullableDirectory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDirectory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


