/*
My API

This is the API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package main

import (
	"encoding/json"
	"fmt"
)

// checks if the ApiGetExectableJobPost200ResponseInnerOutputBindingsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiGetExectableJobPost200ResponseInnerOutputBindingsInner{}

// ApiGetExectableJobPost200ResponseInnerOutputBindingsInner struct for ApiGetExectableJobPost200ResponseInnerOutputBindingsInner
type ApiGetExectableJobPost200ResponseInnerOutputBindingsInner struct {
	Name string `json:"name"`
	SecondaryFiles []ApiGetExectableJobPost200ResponseInnerOutputBindingsInnerSecondaryFilesInner `json:"secondaryFiles"`
	LoadContents *bool `json:"loadContents,omitempty"`
	LoadListing *LoadListingEnum `json:"loadListing,omitempty"`
	Glob []string `json:"glob,omitempty"`
	OutputEval *string `json:"outputEval,omitempty"`
}

type _ApiGetExectableJobPost200ResponseInnerOutputBindingsInner ApiGetExectableJobPost200ResponseInnerOutputBindingsInner

// NewApiGetExectableJobPost200ResponseInnerOutputBindingsInner instantiates a new ApiGetExectableJobPost200ResponseInnerOutputBindingsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiGetExectableJobPost200ResponseInnerOutputBindingsInner(name string, secondaryFiles []ApiGetExectableJobPost200ResponseInnerOutputBindingsInnerSecondaryFilesInner) *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner {
	this := ApiGetExectableJobPost200ResponseInnerOutputBindingsInner{}
	this.Name = name
	this.SecondaryFiles = secondaryFiles
	return &this
}

// NewApiGetExectableJobPost200ResponseInnerOutputBindingsInnerWithDefaults instantiates a new ApiGetExectableJobPost200ResponseInnerOutputBindingsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiGetExectableJobPost200ResponseInnerOutputBindingsInnerWithDefaults() *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner {
	this := ApiGetExectableJobPost200ResponseInnerOutputBindingsInner{}
	return &this
}

// GetName returns the Name field value
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) SetName(v string) {
	o.Name = v
}

// GetSecondaryFiles returns the SecondaryFiles field value
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) GetSecondaryFiles() []ApiGetExectableJobPost200ResponseInnerOutputBindingsInnerSecondaryFilesInner {
	if o == nil {
		var ret []ApiGetExectableJobPost200ResponseInnerOutputBindingsInnerSecondaryFilesInner
		return ret
	}

	return o.SecondaryFiles
}

// GetSecondaryFilesOk returns a tuple with the SecondaryFiles field value
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) GetSecondaryFilesOk() ([]ApiGetExectableJobPost200ResponseInnerOutputBindingsInnerSecondaryFilesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.SecondaryFiles, true
}

// SetSecondaryFiles sets field value
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) SetSecondaryFiles(v []ApiGetExectableJobPost200ResponseInnerOutputBindingsInnerSecondaryFilesInner) {
	o.SecondaryFiles = v
}

// GetLoadContents returns the LoadContents field value if set, zero value otherwise.
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) GetLoadContents() bool {
	if o == nil || IsNil(o.LoadContents) {
		var ret bool
		return ret
	}
	return *o.LoadContents
}

// GetLoadContentsOk returns a tuple with the LoadContents field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) GetLoadContentsOk() (*bool, bool) {
	if o == nil || IsNil(o.LoadContents) {
		return nil, false
	}
	return o.LoadContents, true
}

// HasLoadContents returns a boolean if a field has been set.
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) HasLoadContents() bool {
	if o != nil && !IsNil(o.LoadContents) {
		return true
	}

	return false
}

// SetLoadContents gets a reference to the given bool and assigns it to the LoadContents field.
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) SetLoadContents(v bool) {
	o.LoadContents = &v
}

// GetLoadListing returns the LoadListing field value if set, zero value otherwise.
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) GetLoadListing() LoadListingEnum {
	if o == nil || IsNil(o.LoadListing) {
		var ret LoadListingEnum
		return ret
	}
	return *o.LoadListing
}

// GetLoadListingOk returns a tuple with the LoadListing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) GetLoadListingOk() (*LoadListingEnum, bool) {
	if o == nil || IsNil(o.LoadListing) {
		return nil, false
	}
	return o.LoadListing, true
}

// HasLoadListing returns a boolean if a field has been set.
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) HasLoadListing() bool {
	if o != nil && !IsNil(o.LoadListing) {
		return true
	}

	return false
}

// SetLoadListing gets a reference to the given LoadListingEnum and assigns it to the LoadListing field.
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) SetLoadListing(v LoadListingEnum) {
	o.LoadListing = &v
}

// GetGlob returns the Glob field value if set, zero value otherwise.
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) GetGlob() []string {
	if o == nil || IsNil(o.Glob) {
		var ret []string
		return ret
	}
	return o.Glob
}

// GetGlobOk returns a tuple with the Glob field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) GetGlobOk() ([]string, bool) {
	if o == nil || IsNil(o.Glob) {
		return nil, false
	}
	return o.Glob, true
}

// HasGlob returns a boolean if a field has been set.
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) HasGlob() bool {
	if o != nil && !IsNil(o.Glob) {
		return true
	}

	return false
}

// SetGlob gets a reference to the given []string and assigns it to the Glob field.
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) SetGlob(v []string) {
	o.Glob = v
}

// GetOutputEval returns the OutputEval field value if set, zero value otherwise.
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) GetOutputEval() string {
	if o == nil || IsNil(o.OutputEval) {
		var ret string
		return ret
	}
	return *o.OutputEval
}

// GetOutputEvalOk returns a tuple with the OutputEval field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) GetOutputEvalOk() (*string, bool) {
	if o == nil || IsNil(o.OutputEval) {
		return nil, false
	}
	return o.OutputEval, true
}

// HasOutputEval returns a boolean if a field has been set.
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) HasOutputEval() bool {
	if o != nil && !IsNil(o.OutputEval) {
		return true
	}

	return false
}

// SetOutputEval gets a reference to the given string and assigns it to the OutputEval field.
func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) SetOutputEval(v string) {
	o.OutputEval = &v
}

func (o ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["secondaryFiles"] = o.SecondaryFiles
	if !IsNil(o.LoadContents) {
		toSerialize["loadContents"] = o.LoadContents
	}
	if !IsNil(o.LoadListing) {
		toSerialize["loadListing"] = o.LoadListing
	}
	if !IsNil(o.Glob) {
		toSerialize["glob"] = o.Glob
	}
	if !IsNil(o.OutputEval) {
		toSerialize["outputEval"] = o.OutputEval
	}
	return toSerialize, nil
}

func (o *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"secondaryFiles",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiGetExectableJobPost200ResponseInnerOutputBindingsInner := _ApiGetExectableJobPost200ResponseInnerOutputBindingsInner{}

	err = json.Unmarshal(bytes, &varApiGetExectableJobPost200ResponseInnerOutputBindingsInner)

	if err != nil {
		return err
	}

	*o = ApiGetExectableJobPost200ResponseInnerOutputBindingsInner(varApiGetExectableJobPost200ResponseInnerOutputBindingsInner)

	return err
}

type NullableApiGetExectableJobPost200ResponseInnerOutputBindingsInner struct {
	value *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner
	isSet bool
}

func (v NullableApiGetExectableJobPost200ResponseInnerOutputBindingsInner) Get() *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner {
	return v.value
}

func (v *NullableApiGetExectableJobPost200ResponseInnerOutputBindingsInner) Set(val *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiGetExectableJobPost200ResponseInnerOutputBindingsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiGetExectableJobPost200ResponseInnerOutputBindingsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiGetExectableJobPost200ResponseInnerOutputBindingsInner(val *ApiGetExectableJobPost200ResponseInnerOutputBindingsInner) *NullableApiGetExectableJobPost200ResponseInnerOutputBindingsInner {
	return &NullableApiGetExectableJobPost200ResponseInnerOutputBindingsInner{value: val, isSet: true}
}

func (v NullableApiGetExectableJobPost200ResponseInnerOutputBindingsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiGetExectableJobPost200ResponseInnerOutputBindingsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


