/*
My API

This is the API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package main

import (
	"encoding/json"
	"fmt"
)

// checks if the ApiWorkerStartedPost200ResponseAnyOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiWorkerStartedPost200ResponseAnyOf{}

// ApiWorkerStartedPost200ResponseAnyOf struct for ApiWorkerStartedPost200ResponseAnyOf
type ApiWorkerStartedPost200ResponseAnyOf struct {
	Type string `json:"type"`
	RootUrl string `json:"rootUrl"`
	Prefix *string `json:"prefix,omitempty"`
	Endpoint *string `json:"endpoint,omitempty"`
	AccessKey string `json:"accessKey"`
	SecretKey string `json:"secretKey"`
}

type _ApiWorkerStartedPost200ResponseAnyOf ApiWorkerStartedPost200ResponseAnyOf

// NewApiWorkerStartedPost200ResponseAnyOf instantiates a new ApiWorkerStartedPost200ResponseAnyOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiWorkerStartedPost200ResponseAnyOf(type_ string, rootUrl string, accessKey string, secretKey string) *ApiWorkerStartedPost200ResponseAnyOf {
	this := ApiWorkerStartedPost200ResponseAnyOf{}
	this.Type = type_
	this.RootUrl = rootUrl
	this.AccessKey = accessKey
	this.SecretKey = secretKey
	return &this
}

// NewApiWorkerStartedPost200ResponseAnyOfWithDefaults instantiates a new ApiWorkerStartedPost200ResponseAnyOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiWorkerStartedPost200ResponseAnyOfWithDefaults() *ApiWorkerStartedPost200ResponseAnyOf {
	this := ApiWorkerStartedPost200ResponseAnyOf{}
	return &this
}

// GetType returns the Type field value
func (o *ApiWorkerStartedPost200ResponseAnyOf) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ApiWorkerStartedPost200ResponseAnyOf) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ApiWorkerStartedPost200ResponseAnyOf) SetType(v string) {
	o.Type = v
}

// GetRootUrl returns the RootUrl field value
func (o *ApiWorkerStartedPost200ResponseAnyOf) GetRootUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RootUrl
}

// GetRootUrlOk returns a tuple with the RootUrl field value
// and a boolean to check if the value has been set.
func (o *ApiWorkerStartedPost200ResponseAnyOf) GetRootUrlOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RootUrl, true
}

// SetRootUrl sets field value
func (o *ApiWorkerStartedPost200ResponseAnyOf) SetRootUrl(v string) {
	o.RootUrl = v
}

// GetPrefix returns the Prefix field value if set, zero value otherwise.
func (o *ApiWorkerStartedPost200ResponseAnyOf) GetPrefix() string {
	if o == nil || IsNil(o.Prefix) {
		var ret string
		return ret
	}
	return *o.Prefix
}

// GetPrefixOk returns a tuple with the Prefix field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiWorkerStartedPost200ResponseAnyOf) GetPrefixOk() (*string, bool) {
	if o == nil || IsNil(o.Prefix) {
		return nil, false
	}
	return o.Prefix, true
}

// HasPrefix returns a boolean if a field has been set.
func (o *ApiWorkerStartedPost200ResponseAnyOf) HasPrefix() bool {
	if o != nil && !IsNil(o.Prefix) {
		return true
	}

	return false
}

// SetPrefix gets a reference to the given string and assigns it to the Prefix field.
func (o *ApiWorkerStartedPost200ResponseAnyOf) SetPrefix(v string) {
	o.Prefix = &v
}

// GetEndpoint returns the Endpoint field value if set, zero value otherwise.
func (o *ApiWorkerStartedPost200ResponseAnyOf) GetEndpoint() string {
	if o == nil || IsNil(o.Endpoint) {
		var ret string
		return ret
	}
	return *o.Endpoint
}

// GetEndpointOk returns a tuple with the Endpoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiWorkerStartedPost200ResponseAnyOf) GetEndpointOk() (*string, bool) {
	if o == nil || IsNil(o.Endpoint) {
		return nil, false
	}
	return o.Endpoint, true
}

// HasEndpoint returns a boolean if a field has been set.
func (o *ApiWorkerStartedPost200ResponseAnyOf) HasEndpoint() bool {
	if o != nil && !IsNil(o.Endpoint) {
		return true
	}

	return false
}

// SetEndpoint gets a reference to the given string and assigns it to the Endpoint field.
func (o *ApiWorkerStartedPost200ResponseAnyOf) SetEndpoint(v string) {
	o.Endpoint = &v
}

// GetAccessKey returns the AccessKey field value
func (o *ApiWorkerStartedPost200ResponseAnyOf) GetAccessKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AccessKey
}

// GetAccessKeyOk returns a tuple with the AccessKey field value
// and a boolean to check if the value has been set.
func (o *ApiWorkerStartedPost200ResponseAnyOf) GetAccessKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AccessKey, true
}

// SetAccessKey sets field value
func (o *ApiWorkerStartedPost200ResponseAnyOf) SetAccessKey(v string) {
	o.AccessKey = v
}

// GetSecretKey returns the SecretKey field value
func (o *ApiWorkerStartedPost200ResponseAnyOf) GetSecretKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SecretKey
}

// GetSecretKeyOk returns a tuple with the SecretKey field value
// and a boolean to check if the value has been set.
func (o *ApiWorkerStartedPost200ResponseAnyOf) GetSecretKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SecretKey, true
}

// SetSecretKey sets field value
func (o *ApiWorkerStartedPost200ResponseAnyOf) SetSecretKey(v string) {
	o.SecretKey = v
}

func (o ApiWorkerStartedPost200ResponseAnyOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiWorkerStartedPost200ResponseAnyOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["rootUrl"] = o.RootUrl
	if !IsNil(o.Prefix) {
		toSerialize["prefix"] = o.Prefix
	}
	if !IsNil(o.Endpoint) {
		toSerialize["endpoint"] = o.Endpoint
	}
	toSerialize["accessKey"] = o.AccessKey
	toSerialize["secretKey"] = o.SecretKey
	return toSerialize, nil
}

func (o *ApiWorkerStartedPost200ResponseAnyOf) UnmarshalJSON(bytes []byte) (err error) {
    // This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"rootUrl",
		"accessKey",
		"secretKey",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(bytes, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiWorkerStartedPost200ResponseAnyOf := _ApiWorkerStartedPost200ResponseAnyOf{}

	err = json.Unmarshal(bytes, &varApiWorkerStartedPost200ResponseAnyOf)

	if err != nil {
		return err
	}

	*o = ApiWorkerStartedPost200ResponseAnyOf(varApiWorkerStartedPost200ResponseAnyOf)

	return err
}

type NullableApiWorkerStartedPost200ResponseAnyOf struct {
	value *ApiWorkerStartedPost200ResponseAnyOf
	isSet bool
}

func (v NullableApiWorkerStartedPost200ResponseAnyOf) Get() *ApiWorkerStartedPost200ResponseAnyOf {
	return v.value
}

func (v *NullableApiWorkerStartedPost200ResponseAnyOf) Set(val *ApiWorkerStartedPost200ResponseAnyOf) {
	v.value = val
	v.isSet = true
}

func (v NullableApiWorkerStartedPost200ResponseAnyOf) IsSet() bool {
	return v.isSet
}

func (v *NullableApiWorkerStartedPost200ResponseAnyOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiWorkerStartedPost200ResponseAnyOf(val *ApiWorkerStartedPost200ResponseAnyOf) *NullableApiWorkerStartedPost200ResponseAnyOf {
	return &NullableApiWorkerStartedPost200ResponseAnyOf{value: val, isSet: true}
}

func (v NullableApiWorkerStartedPost200ResponseAnyOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiWorkerStartedPost200ResponseAnyOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


