/*
My API

This is the API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package main

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the MapperEnt type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MapperEnt{}

// MapperEnt struct for MapperEnt
type MapperEnt struct {
	Resolved string `json:"resolved"`
	Target string `json:"target"`
	Type string `json:"type"`
	Staged bool `json:"staged"`
}

type _MapperEnt MapperEnt

// NewMapperEnt instantiates a new MapperEnt object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMapperEnt(resolved string, target string, type_ string, staged bool) *MapperEnt {
	this := MapperEnt{}
	this.Resolved = resolved
	this.Target = target
	this.Type = type_
	this.Staged = staged
	return &this
}

// NewMapperEntWithDefaults instantiates a new MapperEnt object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMapperEntWithDefaults() *MapperEnt {
	this := MapperEnt{}
	return &this
}

// GetResolved returns the Resolved field value
func (o *MapperEnt) GetResolved() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Resolved
}

// GetResolvedOk returns a tuple with the Resolved field value
// and a boolean to check if the value has been set.
func (o *MapperEnt) GetResolvedOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Resolved, true
}

// SetResolved sets field value
func (o *MapperEnt) SetResolved(v string) {
	o.Resolved = v
}

// GetTarget returns the Target field value
func (o *MapperEnt) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *MapperEnt) GetTargetOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *MapperEnt) SetTarget(v string) {
	o.Target = v
}

// GetType returns the Type field value
func (o *MapperEnt) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *MapperEnt) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *MapperEnt) SetType(v string) {
	o.Type = v
}

// GetStaged returns the Staged field value
func (o *MapperEnt) GetStaged() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Staged
}

// GetStagedOk returns a tuple with the Staged field value
// and a boolean to check if the value has been set.
func (o *MapperEnt) GetStagedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Staged, true
}

// SetStaged sets field value
func (o *MapperEnt) SetStaged(v bool) {
	o.Staged = v
}

func (o MapperEnt) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MapperEnt) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resolved"] = o.Resolved
	toSerialize["target"] = o.Target
	toSerialize["type"] = o.Type
	toSerialize["staged"] = o.Staged
	return toSerialize, nil
}

func (o *MapperEnt) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resolved",
		"target",
		"type",
		"staged",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varMapperEnt := _MapperEnt{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varMapperEnt)

	if err != nil {
		return err
	}

	*o = MapperEnt(varMapperEnt)

	return err
}

type NullableMapperEnt struct {
	value *MapperEnt
	isSet bool
}

func (v NullableMapperEnt) Get() *MapperEnt {
	return v.value
}

func (v *NullableMapperEnt) Set(val *MapperEnt) {
	v.value = val
	v.isSet = true
}

func (v NullableMapperEnt) IsSet() bool {
	return v.isSet
}

func (v *NullableMapperEnt) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMapperEnt(val *MapperEnt) *NullableMapperEnt {
	return &NullableMapperEnt{value: val, isSet: true}
}

func (v NullableMapperEnt) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMapperEnt) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


