/*
My API

This is the API

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package main

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the OutputBindingSecondaryFilesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OutputBindingSecondaryFilesInner{}

// OutputBindingSecondaryFilesInner struct for OutputBindingSecondaryFilesInner
type OutputBindingSecondaryFilesInner struct {
	Pattern string `json:"pattern"`
	RequiredBoolean *bool `json:"requiredBoolean,omitempty"`
	RequiredString *string `json:"requiredString,omitempty"`
}

type _OutputBindingSecondaryFilesInner OutputBindingSecondaryFilesInner

// NewOutputBindingSecondaryFilesInner instantiates a new OutputBindingSecondaryFilesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOutputBindingSecondaryFilesInner(pattern string) *OutputBindingSecondaryFilesInner {
	this := OutputBindingSecondaryFilesInner{}
	this.Pattern = pattern
	return &this
}

// NewOutputBindingSecondaryFilesInnerWithDefaults instantiates a new OutputBindingSecondaryFilesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOutputBindingSecondaryFilesInnerWithDefaults() *OutputBindingSecondaryFilesInner {
	this := OutputBindingSecondaryFilesInner{}
	return &this
}

// GetPattern returns the Pattern field value
func (o *OutputBindingSecondaryFilesInner) GetPattern() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Pattern
}

// GetPatternOk returns a tuple with the Pattern field value
// and a boolean to check if the value has been set.
func (o *OutputBindingSecondaryFilesInner) GetPatternOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Pattern, true
}

// SetPattern sets field value
func (o *OutputBindingSecondaryFilesInner) SetPattern(v string) {
	o.Pattern = v
}

// GetRequiredBoolean returns the RequiredBoolean field value if set, zero value otherwise.
func (o *OutputBindingSecondaryFilesInner) GetRequiredBoolean() bool {
	if o == nil || IsNil(o.RequiredBoolean) {
		var ret bool
		return ret
	}
	return *o.RequiredBoolean
}

// GetRequiredBooleanOk returns a tuple with the RequiredBoolean field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputBindingSecondaryFilesInner) GetRequiredBooleanOk() (*bool, bool) {
	if o == nil || IsNil(o.RequiredBoolean) {
		return nil, false
	}
	return o.RequiredBoolean, true
}

// HasRequiredBoolean returns a boolean if a field has been set.
func (o *OutputBindingSecondaryFilesInner) HasRequiredBoolean() bool {
	if o != nil && !IsNil(o.RequiredBoolean) {
		return true
	}

	return false
}

// SetRequiredBoolean gets a reference to the given bool and assigns it to the RequiredBoolean field.
func (o *OutputBindingSecondaryFilesInner) SetRequiredBoolean(v bool) {
	o.RequiredBoolean = &v
}

// GetRequiredString returns the RequiredString field value if set, zero value otherwise.
func (o *OutputBindingSecondaryFilesInner) GetRequiredString() string {
	if o == nil || IsNil(o.RequiredString) {
		var ret string
		return ret
	}
	return *o.RequiredString
}

// GetRequiredStringOk returns a tuple with the RequiredString field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OutputBindingSecondaryFilesInner) GetRequiredStringOk() (*string, bool) {
	if o == nil || IsNil(o.RequiredString) {
		return nil, false
	}
	return o.RequiredString, true
}

// HasRequiredString returns a boolean if a field has been set.
func (o *OutputBindingSecondaryFilesInner) HasRequiredString() bool {
	if o != nil && !IsNil(o.RequiredString) {
		return true
	}

	return false
}

// SetRequiredString gets a reference to the given string and assigns it to the RequiredString field.
func (o *OutputBindingSecondaryFilesInner) SetRequiredString(v string) {
	o.RequiredString = &v
}

func (o OutputBindingSecondaryFilesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OutputBindingSecondaryFilesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pattern"] = o.Pattern
	if !IsNil(o.RequiredBoolean) {
		toSerialize["requiredBoolean"] = o.RequiredBoolean
	}
	if !IsNil(o.RequiredString) {
		toSerialize["requiredString"] = o.RequiredString
	}
	return toSerialize, nil
}

func (o *OutputBindingSecondaryFilesInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"pattern",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varOutputBindingSecondaryFilesInner := _OutputBindingSecondaryFilesInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varOutputBindingSecondaryFilesInner)

	if err != nil {
		return err
	}

	*o = OutputBindingSecondaryFilesInner(varOutputBindingSecondaryFilesInner)

	return err
}

type NullableOutputBindingSecondaryFilesInner struct {
	value *OutputBindingSecondaryFilesInner
	isSet bool
}

func (v NullableOutputBindingSecondaryFilesInner) Get() *OutputBindingSecondaryFilesInner {
	return v.value
}

func (v *NullableOutputBindingSecondaryFilesInner) Set(val *OutputBindingSecondaryFilesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableOutputBindingSecondaryFilesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableOutputBindingSecondaryFilesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOutputBindingSecondaryFilesInner(val *OutputBindingSecondaryFilesInner) *NullableOutputBindingSecondaryFilesInner {
	return &NullableOutputBindingSecondaryFilesInner{value: val, isSet: true}
}

func (v NullableOutputBindingSecondaryFilesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOutputBindingSecondaryFilesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


